"""MetanoiaState - Pydantic state class for LangGraph orchestration.

This module defines the core state structure used throughout the Metanoia-QA
LangGraph state machine, capturing all context needed for multi-agent STLC execution.
"""

from typing import Optional, Any
from datetime import datetime
from enum import Enum
from pydantic import BaseModel, Field

from src.agents.types import AgentType  # Re-export for backward compatibility


class AgentStatus(str, Enum):
    """Agent execution status."""
    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    PAUSED = "paused"


class TestCase(BaseModel):
    """Represents a single test case in the plan."""
    id: str
    title: str
    description: str
    priority: str = Field(..., description="Critical/High/Medium/Low")
    category: str = Field(..., description="Functional/Performance/Security/Integration")
    estimated_duration_minutes: int
    prerequisites: list[str] = Field(default_factory=list)
    steps: list[str] = Field(default_factory=list)
    expected_results: str


class TestPlan(BaseModel):
    """Complete test plan generated by StrategyManager."""
    sprint_id: str
    total_test_cases: int
    estimated_duration_hours: float
    test_cases: list[TestCase] = Field(default_factory=list)
    risk_summary: dict[str, Any] = Field(default_factory=dict)
    effort_allocation: dict[str, float] = Field(default_factory=dict)


class ExecutionResult(BaseModel):
    """Result from an agent execution."""
    agent_id: str
    agent_type: AgentType
    status: AgentStatus
    output: dict[str, Any] = Field(default_factory=dict)
    error: Optional[str] = None
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    duration_seconds: Optional[float] = None


class ReleaseCertification(BaseModel):
    """Release certification decision from ReleaseAnalyst."""
    sprint_id: str
    certified: bool
    confidence_score: float = Field(..., ge=0.0, le=1.0)
    blockers: list[str] = Field(default_factory=list)
    recommendations: list[str] = Field(default_factory=list)
    summary: str
    certified_at: datetime = Field(default_factory=datetime.utcnow)


class MetanoiaState(BaseModel):
    """Main state class for Metanoia-QA LangGraph orchestration.

    This state is passed through the entire STLC pipeline, accumulating
    context from each agent as the graph progresses through its phases.

    Attributes:
        sprint_id: Unique identifier for the sprint being analyzed/executed
        sprint_goal: Description of the sprint's quality mission
        context_analysis: Output from ContextAnalyst's historical analysis
        test_plan: Generated test plan from StrategyManager
        test_cases: Detailed test cases from TestDesignLead
        execution_results: Dictionary mapping agent_id to ExecutionResult
        release_certification: Final certification decision from ReleaseAnalyst
        current_phase: Current STLC phase being executed
        iteration_count: Number of graph iterations (for debugging)
        max_iterations: Maximum allowed iterations (circuit breaker)
    """

    sprint_id: str = Field(..., description="Unique sprint identifier")
    sprint_goal: str = Field(..., description="Sprint quality mission/goal")

    context_analysis: Optional[dict[str, Any]] = Field(
        default=None,
        description="Historical context analysis from ContextAnalyst"
    )
    test_plan: Optional[dict[str, Any]] = Field(
        default=None,
        description="Test plan structure from StrategyManager"
    )
    test_cases: list[TestCase] = Field(
        default_factory=list,
        description="Detailed test cases from TestDesignLead"
    )
    execution_results: dict[str, ExecutionResult] = Field(
        default_factory=dict,
        description="Results from all execution agents"
    )
    release_certification: Optional[ReleaseCertification] = Field(
        default=None,
        description="Release certification decision"
    )

    current_phase: str = Field(
        default="init",
        description="Current STLC phase: init, plan, design, execute, close"
    )
    iteration_count: int = Field(
        default=0,
        description="Current graph iteration count"
    )
    max_iterations: int = Field(
        default=100,
        description="Maximum iterations before circuit breaker triggers"
    )

    started_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="When the sprint processing started"
    )
    updated_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="When the state was last updated"
    )

    model_config = {
        "arbitrary_types_allowed": True,
        "validate_assignment": True,
        "json_schema_extra": {
            "example": {
                "sprint_id": "SPRINT-2024-Q1-001",
                "sprint_goal": "Implement user authentication flow",
                "context_analysis": {
                    "historical_risks": ["login_timeout", "session_hijacking"],
                    "regression_score": 0.65
                },
                "test_plan": {
                    "total_test_cases": 42,
                    "estimated_hours": 16.5
                },
                "current_phase": "execute"
            }
        }
    }

    def update_phase(self, new_phase: str) -> None:
        """Update the current phase and timestamp.

        Args:
            new_phase: The new phase to transition to
        """
        self.current_phase = new_phase
        self.updated_at = datetime.utcnow()

    def increment_iteration(self) -> None:
        """Increment iteration counter and check circuit breaker."""
        self.iteration_count += 1
        self.updated_at = datetime.utcnow()

    def is_circuit_breaker_triggered(self) -> bool:
        """Check if maximum iterations have been reached.

        Returns:
            True if iteration_count >= max_iterations
        """
        return self.iteration_count >= self.max_iterations

    def add_execution_result(self, result: ExecutionResult) -> None:
        """Add an agent execution result to the state.

        Args:
            result: The ExecutionResult to add
        """
        self.execution_results[result.agent_id] = result
        self.updated_at = datetime.utcnow()
