"""Compliance report generator.

Generates compliance reports in various formats (HTML, PDF, Markdown).
"""

from pathlib import Path
from typing import Any

from src.agents.compliance import ComplianceReport


class ReportGenerator:
    """Generates compliance reports in various formats.

    Supports:
    - HTML reports for web viewing
    - PDF reports for official distribution
    - Markdown reports for audit logs
    """

    def __init__(self, template_dir: Path):
        """Initialize the report generator.

        Args:
            template_dir: Directory containing report templates
        """
        self.template_dir = Path(template_dir)
        self._template_cache: dict[str, Any] = {}

    async def generate_html(
        self,
        report: ComplianceReport,
        output_path: Path
    ) -> Path:
        """Generate HTML report.

        Args:
            report: The compliance report to render
            output_path: Path where HTML file should be saved

        Returns:
            Path to the generated HTML file
        """
        html_content = self._render_html_template(report)

        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        with open(output_path, "w", encoding="utf-8") as f:
            f.write(html_content)

        return output_path

    async def generate_pdf(
        self,
        report: ComplianceReport,
        output_path: Path
    ) -> Path:
        """Generate PDF report.

        Args:
            report: The compliance report to render
            output_path: Path where PDF file should be saved

        Returns:
            Path to the generated PDF file
        """
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        try:
            from weasyprint import HTML
            html_content = self._render_html_template(report)
            HTML(string=html_content).write_pdf(str(output_path))
        except ImportError:
            markdown_content = self.generate_markdown(report)
            with open(output_path.with_suffix(".md"), "w") as f:
                f.write(markdown_content)

        return output_path

    def generate_markdown(
        self,
        report: ComplianceReport
    ) -> str:
        """Generate Markdown report for audit logs.

        Args:
            report: The compliance report to render

        Returns:
            Markdown formatted report string
        """
        lines = [
            f"# {report.framework.value.upper()} Compliance Report",
            "",
            f"**Generated:** {report.generated_at.isoformat()}",
            f"**Period:** {report.period_start.date()} to {report.period_end.date()}",
            "",
            "## Executive Summary",
            "",
            f"- **Compliance Score:** {self._calculate_score(report.controls_passed, report.controls_failed, report.controls_not_applicable)}%",
            f"- **Coverage:** {report.coverage_percentage:.1f}%",
            f"- **Controls Passed:** {report.controls_passed}",
            f"- **Controls Failed:** {report.controls_failed}",
            f"- **Not Applicable:** {report.controls_not_applicable}",
            "",
            "## Control Assessment",
            "",
        ]

        if report.gaps:
            lines.append("### Identified Gaps")
            lines.append("")
            for gap in report.gaps:
                lines.append(f"- **{gap.get('control_id', 'UNKNOWN')}**: {gap.get('description', 'No description')}")
            lines.append("")
        else:
            lines.append("### Status: All controls passed assessment.")
            lines.append("")

        if report.evidence:
            lines.append("## Evidence Collected")
            lines.append("")
            evidence_by_type = {}
            for item in report.evidence:
                item_type = item.get("type", "unknown")
                if item_type not in evidence_by_type:
                    evidence_by_type[item_type] = 0
                evidence_by_type[item_type] += 1

            for evidence_type, count in evidence_by_type.items():
                lines.append(f"- **{evidence_type}**: {count} items")
            lines.append("")

        lines.append("## Recommendation")
        lines.append("")
        lines.append(report.recommendation)
        lines.append("")
        lines.append("---")
        lines.append("*This report was automatically generated by Metanoia-QA*")

        return "\n".join(lines)

    def _render_html_template(self, report: ComplianceReport) -> str:
        """Render HTML from report data."""
        compliance_score = self._calculate_score(
            report.controls_passed,
            report.controls_failed,
            report.controls_not_applicable
        )

        status_class = "pass" if compliance_score >= 80 else "fail"
        status_text = "PASS" if compliance_score >= 80 else "FAIL"

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{report.framework.value.upper()} Compliance Report</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            max-width: 900px;
            margin: 0 auto;
            padding: 20px;
            color: #333;
        }}
        .header {{
            border-bottom: 2px solid #e0e0e0;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }}
        h1 {{ color: #1a1a1a; margin-bottom: 10px; }}
        h2 {{ color: #333; margin-top: 30px; }}
        .meta {{
            color: #666;
            font-size: 0.9em;
        }}
        .score-card {{
            display: inline-block;
            padding: 20px 40px;
            border-radius: 8px;
            text-align: center;
            margin: 20px 0;
        }}
        .score-card.pass {{ background: #e8f5e9; }}
        .score-card.fail {{ background: #ffebee; }}
        .score-value {{
            font-size: 3em;
            font-weight: bold;
            color: inherit;
        }}
        .score-label {{
            font-size: 0.9em;
            text-transform: uppercase;
        }}
        .metrics {{
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 15px;
            margin: 20px 0;
        }}
        .metric {{
            background: #f5f5f5;
            padding: 15px;
            border-radius: 8px;
            text-align: center;
        }}
        .metric-value {{
            font-size: 1.5em;
            font-weight: bold;
            color: #1a1a1a;
        }}
        .metric-label {{
            font-size: 0.8em;
            color: #666;
        }}
        .gaps {{ background: #ffebee; padding: 20px; border-radius: 8px; }}
        .gap-item {{
            background: white;
            padding: 10px;
            margin: 10px 0;
            border-radius: 4px;
            border-left: 4px solid #ef5350;
        }}
        .evidence-list {{
            background: #f5f5f5;
            padding: 20px;
            border-radius: 8px;
        }}
        .footer {{
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #e0e0e0;
            color: #999;
            font-size: 0.8em;
            text-align: center;
        }}
    </style>
</head>
<body>
    <div class="header">
        <h1>{report.framework.value.upper()} Compliance Report</h1>
        <div class="meta">
            Generated: {report.generated_at.strftime('%Y-%m-%d %H:%M:%S UTC')}<br>
            Period: {report.period_start.date()} to {report.period_end.date()}
        </div>
    </div>

    <div class="score-card {status_class}">
        <div class="score-value">{compliance_score}%</div>
        <div class="score-label">{status_text}</div>
    </div>

    <div class="metrics">
        <div class="metric">
            <div class="metric-value">{report.controls_passed}</div>
            <div class="metric-label">Passed</div>
        </div>
        <div class="metric">
            <div class="metric-value">{report.controls_failed}</div>
            <div class="metric-label">Failed</div>
        </div>
        <div class="metric">
            <div class="metric-value">{report.controls_not_applicable}</div>
            <div class="metric-label">N/A</div>
        </div>
        <div class="metric">
            <div class="metric-value">{report.coverage_percentage:.1f}%</div>
            <div class="metric-label">Coverage</div>
        </div>
    </div>

    <h2>Identified Gaps</h2>
"""

        if report.gaps:
            html += '<div class="gaps">\n'
            for gap in report.gaps:
                html += f"""        <div class="gap-item">
            <strong>{gap.get('control_id', 'UNKNOWN')}</strong>: {gap.get('description', 'No description')}
        </div>
"""
            html += "    </div>\n"
        else:
            html += "    <p>No gaps identified - all controls passed assessment.</p>\n"

        if report.evidence:
            evidence_by_type = {}
            for item in report.evidence:
                item_type = item.get("type", "unknown")
                if item_type not in evidence_by_type:
                    evidence_by_type[item_type] = 0
                evidence_by_type[item_type] += 1

            html += """
    <h2>Evidence Collected</h2>
    <div class="evidence-list">
"""
            for evidence_type, count in evidence_by_type.items():
                html += f"        <div><strong>{evidence_type}</strong>: {count} items</div>\n"
            html += "    </div>\n"

        html += f"""
    <h2>Recommendation</h2>
    <p>{report.recommendation}</p>

    <div class="footer">
        <p>This report was automatically generated by Metanoia-QA Compliance Agent</p>
    </div>
</body>
</html>
"""
        return html

    def _calculate_score(
        self,
        controls_passed: int,
        controls_failed: int,
        controls_na: int
    ) -> float:
        """Calculate compliance score percentage."""
        total_applicable = controls_passed + controls_failed
        if total_applicable == 0:
            return 100.0
        return round((controls_passed / total_applicable) * 100, 2)
